Repository BF-FrontEnd-class-2025/group-2-all-about-trees, pull requests merged in 2025-01, with the labels that each got.

#3 add definition
  README.md
Labels: description, md

#5 add constraints info
  planning/constraints.md
Labels: description, md

#9 add user personas
  planning/user-personas.md
Labels: description, md

#13 add design wireframe
  planning/design.md
  planning/user-personas.md
  planning/wireframe.png
Labels: description, md

#16 add development strategy
  planning/development-strategy.md
Labels: description, md

#29 add header
  index.html
  public/happy-tree.jpg
  styles/something.css
Labels: HTML, CSS

#30 add navbar and footer
  index.html
  styles/index.css
  styles/something.css
Labels: HTML, CSS

#31 add main content
  index.html
  styles/something.css
Labels: HTML, CSS

#27 add sidebar
  index.html
  styles/something.css
Labels: HTML, CSS

#35 fix the title
  styles/something.css
Labels: HTML, CSS

#37 fix Bottom divider
  styles/something.css
Labels: CSS

#41 update readme
  .cspell.json
  README.md
  planning/screenshot-trees.png
Labels: description, md

#40 add Retrospective
  planning/retrospective.md
Labels: md

#44 add toggle
  index.html
  planning/togg.webp
  public/happy-tree.jpg
  public/happy-tree.png
  styles/something.css
Labels: js

#45 add hover effect
  index.html
  styles/something.css
Labels: HTML, CSS
